SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBVACINA;
CREATE DATABASE DBVACINA;
USE DBVACINA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR (100) NOT NULL
    , DT_NASCIMENTO DATE
    , SEXO ENUM ('M', 'F')
    , CPF VARCHAR (11)
    , VOLUNTARIO BOOLEAN
    , PRIMARY KEY (IDPESSOA)
);

CREATE TABLE PESQUISADOR (
  	IDPESQUISADOR INT NOT NULL AUTO_INCREMENT    
    , INSTITUICAO VARCHAR (256)
    , PRIMARY KEY (IDPESQUISADOR)    
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , IDPESQUISADOR INT NOT NULL
    , PAIS_ORIGEM VARCHAR(45)
    , ESTAGIO_PESQUISA ENUM ('1', '2', '3')
    , DT_INICIO DATE     
    , PRIMARY KEY (IDVACINA)
    , FOREIGN KEY (IDPESQUISADOR) REFERENCES PESQUISADOR (IDPESQUISADOR)
);

CREATE TABLE VACINACAO (
	IDVACINACAO INT NOT NULL AUTO_INCREMENT
    , IDVACINA INT NOT NULL
    , IDPESSOA INT NOT NULL
    , DT_VACINACAO DATE
    , AVALIACAO ENUM ('1', '2', '3', '4', '5')
    , PRIMARY KEY (IDVACINACAO)
    , FOREIGN KEY (IDVACINA) REFERENCES VACINA (IDVACINA)
    , FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA)
);
